#!/usr/bin/env bash

xbps-install -Syu terminus-font gptfdisk parted
setfont ter-v32b

################################################
#                                              #
# Create a .env file containing these options: #
#                                              #
################################################
#
# USERNAME=<New user name>
# PASSWORD=<New user password>
# HOSTNAME=<Hostname eg: macbook>
# SHELL=<eg: /bin/bash>
# TOKEN=<Your Github token (PAT)>
# DISK=<eg: /dev/sda>
# MOUNT_OPTIONS=<eg for ssd add: "noatime,ssd,...">
# FS=<Filesystem eg: ext4, btrfs...>
# TIMEZONE=<eg: Europe/Paris>
# KEYMAP=<eg: us,uk,es...>
# REPO=<https://repo-default.voidlinux.org/current>
# ARCH=<x86_64, i686, arm...>

source .env

# Logo
clear
echo -ne "
------------------------------------------------------------------------------------------
                       /$$    /$$         /$$       /$$          
                      | $$   | $$        |__/      | $$          
                      | $$   | $$/$$$$$$  /$$  /$$$$$$$ /$$   /$$                        
                      |  $$ / $$/$$__  $$| $$ /$$__  $$| $$  | $$
                       \  $$ $$/ $$  \ $$| $$| $$  | $$| $$  | $$
                        \  $$$/| $$  | $$| $$| $$  | $$| $$  | $$
                         \  $/ |  $$$$$$/| $$|  $$$$$$$|  $$$$$$$
                          \_/   \______/ |__/ \_______/ \____  $$
                                                        /$$  | $$
                                                       |  $$$$$$/
                                                        \______/
------------------------------------------------------------------------------------------
                               Automated Voidy Installer
------------------------------------------------------------------------------------------
"

echo -ne "
                               Press any key to continue...
"
read

echo -ne "
------------------------------------------------------------------------------------------
                                   Formating Disks
------------------------------------------------------------------------------------------
"
umount -A --recursive /mnt
sgdisk -Z ${DISK}
sgdisk -a 2048 -o ${DISK}

sgdisk -n 1::+128M --typecode=1:af00 --change-name=1:'Boot Loader' ${DISK}
sgdisk -n 2::+256M --typecode=2:8300 --change-name=2:'Boot' ${DISK}
sgdisk -n 3::-0 --typecode=3:8300 --change-name=3:'Root' ${DISK}

if [[ ! -d "/sys/firmware/efi" ]]; then
    sgdisk -A 1:set:2 ${DISK}
fi
partprobe ${DISK}

echo -ne "
------------------------------------------------------------------------------------------
                                  Creating Filesystems
------------------------------------------------------------------------------------------
"
partition2=${DISK}2
partition3=${DISK}3

mkfs.vfat ${partition2}
mkfs.ext4 -L Root ${partition3}
mount -t ext4 ${partition3} /mnt

mkdir /mnt/boot
mount ${partition2} /mnt/boot/

if ! grep -qs '/mnt' /proc/mounts; then
    echo "Drive is not mounted, can not continue"
    echo "Rebooting in 3 Seconds ..." && sleep 1
    echo "Rebooting in 2 Seconds ..." && sleep 1
    echo "Rebooting in 1 Second ..." && sleep 1
    reboot now
fi

echo -ne "
------------------------------------------------------------------------------------------
                                   Voidy Installation 
------------------------------------------------------------------------------------------
"
mkdir -p /mnt/var/db/xbps/keys
cp /var/db/xbps/keys/* /mnt/var/db/xbps/keys/

XBPS_ARCH=$ARCH xbps-install -Sy -r /mnt -R "$REPO" base-system

echo -ne "
------------------------------------------------------------------------------------------
                                   Generating fstab
------------------------------------------------------------------------------------------
"
cp /proc/mounts /mnt/etc/fstab
echo " 
  Generated /etc/fstab:
"
cat /mnt/etc/fstab

echo -ne "
------------------------------------------------------------------------------------------
                            chrooting Into The New Installation
------------------------------------------------------------------------------------------
"
mount --rbind /sys /mnt/sys && mount --make-rslave /mnt/sys
mount --rbind /dev /mnt/dev && mount --make-rslave /mnt/dev
mount --rbind /proc /mnt/proc && mount --make-rslave /mnt/proc

echo "Copying configuration files..."
cp -fvr /etc/resolv.conf /mnt/etc/
cp -fvr /root/voidy/postinstall /root/voidy/.env /mnt/root && echo "Copied successfully"

( chroot /mnt /root/postinstall ) |& tee postinstall.log
cp -fvr postinstall.log /mnt/root
