#!/usr/bin/env bash

xbps-install -Syu terminus-font gptfdisk parted
setfont ter-v32b

################################################
#                                              #
# Create a .env file containing these options: #
#                                              #
################################################
#
# USERNAME=<New user name>
# PASSWORD=<New user password>
# HOSTNAME=<Hostname eg: macbook>
# SHELL=<eg: /bin/bash>
# TOKEN=<Your Github token (PAT)>
# DISK=<eg: /dev/sda>
# MOUNT_OPTIONS=<eg for ssd add: "noatime,ssd,...">
# FS=<Filesystem eg: ext4, btrfs...>
# TIMEZONE=<eg: Europe/Paris>
# KEYMAP=<eg: us,uk,es...>
# REPO=<https://repo-default.voidlinux.org/current>
# ARCH=<x86_64, i686, arm...>

source .env

# Logo
clear
echo -ne "
------------------------------------------------------------------------------------------
                       /$$    /$$         /$$       /$$          
                      | $$   | $$        |__/      | $$          
                      | $$   | $$/$$$$$$  /$$  /$$$$$$$ /$$   /$$                        
                      |  $$ / $$/$$__  $$| $$ /$$__  $$| $$  | $$
                       \  $$ $$/ $$  \ $$| $$| $$  | $$| $$  | $$
                        \  $$$/| $$  | $$| $$| $$  | $$| $$  | $$
                         \  $/ |  $$$$$$/| $$|  $$$$$$$|  $$$$$$$
                          \_/   \______/ |__/ \_______/ \____  $$
                                                        /$$  | $$
                                                       |  $$$$$$/
                                                        \______/
------------------------------------------------------------------------------------------
                               Automated Voidy Installer
------------------------------------------------------------------------------------------
"

echo -ne "
                               Press any key to continue...
"
read

echo -ne "
------------------------------------------------------------------------------------------
                                   Formating Disks
------------------------------------------------------------------------------------------
"
umount -A --recursive /mnt
sgdisk -Z ${DISK}
sgdisk -a 2048 -o ${DISK}

sgdisk -n 1::+256M  --typecode=1:AF00 --change-name=1:'ESP'  ${DISK}
# sgdisk -n 3::+4096M --typecode=3:8200 --change-name=3:'SWAP' ${DISK}
sgdisk -n 2::-0     --typecode=2:8300 --change-name=2:'ROOT' ${DISK}

partprobe ${DISK}

echo -ne "
------------------------------------------------------------------------------------------
                                  Creating Filesystems
------------------------------------------------------------------------------------------
"
mkfs.fat -F 32 ${DISK}1
fatlabel ${DISK}1 ESP
mkfs.ext4 -L ROOT ${DISK}2
# mkswap -L SWAP ${DISK}3

# swapon /dev/disk/by-label/SWAP
mount /dev/disk/by-label/ROOT /mnt
mkdir -p /mnt/boot/efi
mount /dev/disk/by-label/ESP /mnt/boot/efi

if ! grep -qs '/mnt' /proc/mounts; then
  (sleep 3 && reboot )
fi

echo -ne "
------------------------------------------------------------------------------------------
                                   Voidy Installation 
------------------------------------------------------------------------------------------
"
mkdir -p /mnt/var/db/xbps/keys
cp /var/db/xbps/keys/* /mnt/var/db/xbps/keys/

XBPS_ARCH=$ARCH xbps-install -Sy -r /mnt -R "$REPO" base-system linux-lts linux-lts-headers

echo -ne "
------------------------------------------------------------------------------------------
                                   Generating fstab
------------------------------------------------------------------------------------------
"
cp /proc/mounts /mnt/etc/fstab

echo -ne "
------------------------------------------------------------------------------------------
                            chrooting Into The New Installation
------------------------------------------------------------------------------------------
"
mount --rbind /sys /mnt/sys && mount --make-rslave /mnt/sys
mount --rbind /dev /mnt/dev && mount --make-rslave /mnt/dev
mount --rbind /proc /mnt/proc && mount --make-rslave /mnt/proc

echo "Copying configuration files..."
cp -fvr /etc/resolv.conf /mnt/etc/
cp -fvr /root/voidy/postinstall /root/voidy/user /root/voidy/packages /root/voidy/.env /mnt

( chroot /mnt /postinstall ) |& tee postinstall.log
( chroot /mnt /usr/bin/runuser -u ${USERNAME} -- /user ) |& tee user.log
cp -fvr postinstall.log user.log /mnt
