#!/usr/bin/env bash

source .env

clear
echo -ne "
------------------------------------------------------------------------------------------
                       /$$    /$$         /$$       /$$          
                      | $$   | $$        |__/      | $$          
                      | $$   | $$/$$$$$$  /$$  /$$$$$$$ /$$   /$$                        
                      |  $$ / $$/$$__  $$| $$ /$$__  $$| $$  | $$
                       \  $$ $$/ $$  \ $$| $$| $$  | $$| $$  | $$
                        \  $$$/| $$  | $$| $$| $$  | $$| $$  | $$
                         \  $/ |  $$$$$$/| $$|  $$$$$$$|  $$$$$$$
                          \_/   \______/ |__/ \_______/ \____  $$
                                                        /$$  | $$
                                                       |  $$$$$$/
                                                        \______/
------------------------------------------------------------------------------------------
                               Automated Voidy Installer
------------------------------------------------------------------------------------------

"
echo -ne "
------------------------------------------------------------------------------------------
                                   Install packages
------------------------------------------------------------------------------------------
"
xbps-install -S git neovim grub-x86_64-efi

echo -ne "
------------------------------------------------------------------------------------------
                                Setup Language And Locale
------------------------------------------------------------------------------------------
"
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/default/libc-locales
xbps-reconfigure -fv glibc-locales 

echo -ne "
------------------------------------------------------------------------------------------
                                     Adding User
------------------------------------------------------------------------------------------
"
pwconv
echo "${USERNAME}:${PASSWORD}" | chpasswd
echo "${HOSTNAME}" > /etc/hostname

echo -ne "
------------------------------------------------------------------------------------------
                                 Creating GRUB Boot Menu
------------------------------------------------------------------------------------------
"
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub
# sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& rootflags=data=writeback libata.force=1:noncq acpi_osi=!Darwin/' /etc/default/grub
sed -i 's/^GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
sed -i 's/^#GRUB_DISABLE_SUBMENU=y/GRUB_DISABLE_SUBMENU=y/' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

echo -ne "
------------------------------------------------------------------------------------------
                               Managing Essential Services
------------------------------------------------------------------------------------------
"

echo -ne "
------------------------------------------------------------------------------------------
                              Changing Default Console Font
------------------------------------------------------------------------------------------
"
# echo -ne 'KEYMAP="us"
# FONT="ter-v32b"
# ' > /etc/vconsole.conf

echo -ne "
------------------------------------------------------------------------------------------
                                   Github Configuration      
------------------------------------------------------------------------------------------
"
echo -ne "https://nemo256:${TOKEN}@github.com" > ${HOME}/.git-credentials

echo -ne "
------------------------------------------------------------------------------------------
                                Installing Dwm, St, Dmenu...
------------------------------------------------------------------------------------------
"
# cd /root/.build
# Building and installing using make
# cd dwm && make clean install
# cd ../st && make clean install
# cd ../dmenu && make clean install
# cd ../slock && make clean install
# cd ../slstatus && make clean install
# cd ../ani-cli && chmod +x ani-cli && cp ani-cli /usr/local/bin/ani-cli
# cd ../tty-clock && make && make install
# cd ../grabc && make && make install
# cd ../tremc && make install
# yarn global add @aweary/alder
# yarn global add weather-cli

echo -ne "
------------------------------------------------------------------------------------------
                                 Restoring Home Directory
------------------------------------------------------------------------------------------
"
cd $HOME && mkdir Downloads Videos Music Work

echo -ne "
------------------------------------------------------------------------------------------
                                Stowing Configuration Files
------------------------------------------------------------------------------------------
"
# rm -fvr ${HOME}/.bash*
# rm -fvr ${HOME}/.gitconfig
# rm -fvr ${HOME}/.config/*

# cd $HOME/.dotfiles

# stow abook
# stow alsa
# stow bin
# stow bash
# stow dunst
# stow git
# stow gtk-2.0
# stow gtk-3.0
# stow htop
# stow irssi
# stow mbsync
# stow mimeapps
# stow mpd
# stow mpv
# stow mutt
# stow ncmpcpp
# stow neofetch
# stow newsboat
# stow notmuch
# stow nvim
# stow picom
# stow ranger
# stow sxiv
# stow transmission-daemon
# stow tremc
# stow weather-cli-nodejs
# stow xinit
# stow yarn
# stow zathura

# chmod -R 755 $HOME/bin

echo -ne "
------------------------------------------------------------------------------------------
                                   Neovim Configuration
------------------------------------------------------------------------------------------
"

echo -ne "
------------------------------------------------------------------------------------------
                                   Ranger Configuration
------------------------------------------------------------------------------------------
"
# git clone https://github.com/alexanderjeurissen/ranger_devicons \
#   $HOME/.config/ranger/plugins/ranger_devicons

# cd $HOME/.config/ranger/plugins/ranger_devicons/
# python -m devicons
# cd $HOME

echo -ne "
------------------------------------------------------------------------------------------
                                   Firefox Configuration
------------------------------------------------------------------------------------------
"
# firefox

# prefs=$(find $HOME/.mozilla/ -name '*prefs.js')

# echo -ne '
# user_pref("network.protocol-handler.expose.magnet", false);
# ' >> $prefs

echo -ne "
------------------------------------------------------------------------------------------
                                    Fonts Configuration
------------------------------------------------------------------------------------------
"
# mkdir -p ${HOME}/.fonts
# cd ${HOME}/.fonts && curl -fLo "Fira Code Bold Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Bold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete.ttf

# fc-cache -f -v

# cd $HOME

echo -ne "
------------------------------------------------------------------------------------------
                                   Disabling Screen Tear
------------------------------------------------------------------------------------------
"
# echo -ne 'Section "Device"
#   Identifier "Intel Graphics"
#   Driver "intel"
#   Option "TearFree" "true"
# EndSection
# ' > /etc/X11/xorg.conf.d/20-intel.conf

echo -ne "
------------------------------------------------------------------------------------------
                                    Slock Configuration
------------------------------------------------------------------------------------------
"
# echo -ne '[Unit]
# Description=Lock X session using slock for user %i
# Before=sleep.target

# [Service]
# User=%i
# Environment=DISPLAY=:0
# ExecStartPre=/usr/bin/xset dpms force suspend
# ExecStart=/usr/local/bin/slock

# [Install]
# WantedBy=sleep.target
# ' > /etc/systemd/system/slock@.service

echo -ne "
------------------------------------------------------------------------------------------
                               Updating Touchpad Configuration
------------------------------------------------------------------------------------------
"
# echo -ne 'Section "InputClass"
#     Identifier "libinput touchpad catchall"
#     MatchIsTouchpad "on"
#     MatchDevicePath "/dev/input/event*"
#     Option "Tapping" "True"
#     Option "TappingDrag" "True"
#     Option "ScrollMethod" "Twofinger"
#     Option "NaturalScrolling" "False"
#     Option "DisableWhileTyping" "False"
#     Driver "libinput"
# EndSection
# ' > /etc/X11/xorg.conf.d/40-libinput.conf

echo -ne "
------------------------------------------------------------------------------------------
                               Re-enabling Essential Services
------------------------------------------------------------------------------------------
"
ln -sf /etc/sv/dhcpcd /var/service
# Enabling slock to lock screen on suspend / sleep
# systemctl enable slock@$(whoami).service
# echo "  Slock enabled!"

echo -ne "
------------------------------------------------------------------------------------------
                                         Cleaning
------------------------------------------------------------------------------------------
"
# sed -i 's/^%wheel ALL=(ALL) NOPASSWD: ALL/# %wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers
# sed -i 's/^%wheel ALL=(ALL:ALL) NOPASSWD: ALL/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
# Add sudo rights
# sed -i 's/^# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers
# sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

# rm -fvr $HOME/.postinstall $HOME/.env

echo -ne "
------------------------------------------------------------------------------------------
                       /$$    /$$         /$$       /$$          
                      | $$   | $$        |__/      | $$          
                      | $$   | $$/$$$$$$  /$$  /$$$$$$$ /$$   /$$                        
                      |  $$ / $$/$$__  $$| $$ /$$__  $$| $$  | $$
                       \  $$ $$/ $$  \ $$| $$| $$  | $$| $$  | $$
                        \  $$$/| $$  | $$| $$| $$  | $$| $$  | $$
                         \  $/ |  $$$$$$/| $$|  $$$$$$$|  $$$$$$$
                          \_/   \______/ |__/ \_______/ \____  $$
                                                        /$$  | $$
                                                       |  $$$$$$/
                                                        \______/
------------------------------------------------------------------------------------------
                               Automated Voidy Installer
------------------------------------------------------------------------------------------
                            Done - Please Eject Install Media

"
