#!/usr/bin/env bash

source .env

clear
echo -ne "
------------------------------------------------------------------------------------------
                       /$$    /$$         /$$       /$$          
                      | $$   | $$        |__/      | $$          
                      | $$   | $$/$$$$$$  /$$  /$$$$$$$ /$$   /$$                        
                      |  $$ / $$/$$__  $$| $$ /$$__  $$| $$  | $$
                       \  $$ $$/ $$  \ $$| $$| $$  | $$| $$  | $$
                        \  $$$/| $$  | $$| $$| $$  | $$| $$  | $$
                         \  $/ |  $$$$$$/| $$|  $$$$$$$|  $$$$$$$
                          \_/   \______/ |__/ \_______/ \____  $$
                                                        /$$  | $$
                                                       |  $$$$$$/
                                                        \______/
------------------------------------------------------------------------------------------
                               Automated Voidy Installer
------------------------------------------------------------------------------------------

"
echo -ne "
------------------------------------------------------------------------------------------
                                Setup Language And Locale
------------------------------------------------------------------------------------------
"
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/default/libc-locales
xbps-reconfigure -fv glibc-locales 

echo -ne "
------------------------------------------------------------------------------------------
                                     Adding User
------------------------------------------------------------------------------------------
"
groupadd libvirt
useradd -m -G wheel,libvirt -s /bin/bash --badname ${USERNAME}
echo "root:${MASTER_PASSWORD}" | chpasswd
echo "${USERNAME}:${PASSWORD}" | chpasswd
echo "${HOSTNAME}" > /etc/hostname

echo -ne "
------------------------------------------------------------------------------------------
                                   Generating fstab
------------------------------------------------------------------------------------------
"
UUIDs=$(blkid | grep -Eo "UUID=\".*\"" | cut -d "\"" -f2)

echo "# <file system> <mount point> <type> <options> <dump> <pass>" > /etc/fstab
for UUID in $UUIDs; do
  TYPE=$(blkid | grep $UUID | sed -n 's/.*TYPE="\([^"]*\)".*/\1/p')
  if [ "${TYPE}" == "vfat" ]; then
    echo "UUID=$UUID /boot/efi vfat defaults 0 2" >> /etc/fstab
  elif [ "${TYPE}" == "ext4" ]; then
    echo "UUID=$UUID / ext4 defaults,discard 0 1" >> /etc/fstab
  elif [ "${TYPE}" == "swap" ]; then
    echo "UUID=$UUID swap swap rw,noatime,discard 0 0" >> /etc/fstab
  fi
done

chmod 644 /etc/fstab

echo -ne "
------------------------------------------------------------------------------------------
                                 Creating GRUB Boot Menu
------------------------------------------------------------------------------------------
"
xbps-install -S -y git neovim grub-x86_64-efi void-repo-nonfree
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub
# sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& rootflags=data=writeback libata.force=1:noncq acpi_osi=!Darwin/' /etc/default/grub
sed -i 's/^GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
sed -i 's/^#GRUB_DISABLE_SUBMENU=y/GRUB_DISABLE_SUBMENU=y/' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

echo -ne "
------------------------------------------------------------------------------------------
                                  Installing packages
------------------------------------------------------------------------------------------
"
# if [[ ! -f "packages" ]]; then
#   echo "Error: packages file not found."
#   exit 1
# fi
#
# while read line
# do
#   if [[ $line == "" ]] || [[ $line == \#* ]]; then
#     continue
#   fi
#   xbps-install -S -y "$line"
# done < packages

echo -ne "
------------------------------------------------------------------------------------------
                              Changing Default Console Font
------------------------------------------------------------------------------------------
"
# echo -ne 'KEYMAP="us"
# FONT="ter-v32b"
# ' > /etc/vconsole.conf

echo -ne "
------------------------------------------------------------------------------------------
                                   Disabling Screen Tear
------------------------------------------------------------------------------------------
"
echo -ne 'Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
  Option "TearFree" "true"
EndSection
' > /etc/X11/xorg.conf.d/20-intel.conf

echo -ne "
------------------------------------------------------------------------------------------
                                    Slock Configuration
------------------------------------------------------------------------------------------
"
echo -ne '[Unit]
Description=Lock X session using slock for user %i
Before=sleep.target

[Service]
User=%i
Environment=DISPLAY=:0
ExecStartPre=/usr/bin/xset dpms force suspend
ExecStart=/usr/local/bin/slock

[Install]
WantedBy=sleep.target
' > /etc/systemd/system/slock@.service

echo -ne "
------------------------------------------------------------------------------------------
                               Updating Touchpad Configuration
------------------------------------------------------------------------------------------
"
echo -ne 'Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Option "Tapping" "True"
    Option "TappingDrag" "True"
    Option "ScrollMethod" "Twofinger"
    Option "NaturalScrolling" "False"
    Option "DisableWhileTyping" "False"
    Driver "libinput"
EndSection
' > /etc/X11/xorg.conf.d/40-libinput.conf

echo -ne "
------------------------------------------------------------------------------------------
                               Re-enabling Essential Services
------------------------------------------------------------------------------------------
"
ln -sf /etc/sv/dhcpcd /var/service
# systemctl enable slock@$(whoami).service

echo -ne "
------------------------------------------------------------------------------------------
                                Add no password sudo rights
------------------------------------------------------------------------------------------
"
sed -ni "/^root/{a\
  ${USERNAME} ALL=(ALL:ALL) NOPASSWD: ALL
p}" /etc/sudoers
