#!/usr/bin/env bash

# Get environment variables
source .env

# Home directory
cd ${HOME}

# Install paru
# git clone https://aur.archlinux.org/paru-bin.git
# cd paru-bin
# makepkg -si --noconfirm

echo -ne "
------------------------------------------------------------------------------------------
                                   Github Configuration      
------------------------------------------------------------------------------------------
"
echo -ne "https://nemo256:${TOKEN}@github.com" > ${HOME}/.git-credentials
git config --global credential.helper store

echo -ne "
------------------------------------------------------------------------------------------
                                  Installing from github
------------------------------------------------------------------------------------------
"
cd ${HOME}
[[ ! -d .dotfiles ]] \
  && git clone https://github.com/nemo256/.dotfiles
# [[ ! -d Documents ]] \
#   && git clone https://github.com/nemo256/Documents
# [[ ! -d Pictures ]] \
#   && git clone https://github.com/nemo256/Pictures
# [[ ! -d Music ]] \
#   && git clone https://github.com/nemo256/Music
# [[ ! -d Templates ]] \
#   && git clone https://github.com/nemo256/Templates

# Preparing dwm, st, dmenu...
[[ ! -d .build ]] && mkdir .build
cd .build
[[ ! -d dwm ]] \
  && git clone https://github.com/nemo256/dwm
[[ ! -d st ]] \
  && git clone https://github.com/nemo256/st
[[ ! -d dmenu ]] \
  && git clone https://github.com/nemo256/dmenu
[[ ! -d slstatus ]] \
  && git clone https://github.com/nemo256/slstatus
[[ ! -d slock ]] \
  && git clone https://github.com/nemo256/slock
[[ ! -d ani-cli ]] \
  && git clone https://github.com/pystardust/ani-cli
[[ ! -d tty-clock ]] \
  && git clone https://github.com/xorg62/tty-clock
[[ ! -d grabc ]] \
  && git clone https://github.com/muquit/grabc
[[ ! -d tremc ]] \
  && git clone https://github.com/tremc/tremc

cd ${HOME}/.build
cd dwm && sudo make clean install
cd ../st && sudo make clean install
cd ../dmenu && sudo make clean install
cd ../slock && sudo make clean install
cd ../slstatus && sudo make clean install
cd ../ani-cli && sudo chmod +x ani-cli && sudo cp -fvr ani-cli /usr/local/bin/ani-cli
cd ../tty-clock && make && sudo make install
cd ../grabc && make && sudo make install
cd ../tremc && sudo make install
yarn global add @aweary/alder
yarn global add weather-cli

echo -ne "
------------------------------------------------------------------------------------------
                                 Restoring Home Directory
------------------------------------------------------------------------------------------
"
cd ${HOME} && mkdir Videos Work

echo -ne "
------------------------------------------------------------------------------------------
                                Stowing Configuration Files
------------------------------------------------------------------------------------------
"
rm -fvr ${HOME}/.bash*
rm -fvr ${HOME}/.gitconfig
rm -fvr ${HOME}/.config/*

cd ${HOME}/.dotfiles

stow abook
stow bin
stow bash
stow dunst
stow git
stow gtk-2.0
stow gtk-3.0
stow htop
stow irssi
stow mbsync
stow mimeapps
stow mpd
stow mpv
stow mutt
stow ncmpcpp
stow neofetch
stow newsboat
stow notmuch
stow nvim
stow picom
stow ranger
stow sxiv
stow transmission-daemon
stow tremc
stow weather-cli-nodejs
stow xinit
stow yarn
stow zathura

chmod -R 755 ${HOME}/bin

echo -ne "
------------------------------------------------------------------------------------------
                                   Vimy Configuration
------------------------------------------------------------------------------------------
"
git clone https://github.com/nemo256/vimy \
  ${HOME}/.config/nvim

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
  ${HOME}/.local/share/nvim/site/pack/packer/start/packer.nvim

nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

echo -ne "
------------------------------------------------------------------------------------------
                                   Ranger Configuration
------------------------------------------------------------------------------------------
"
git clone https://github.com/alexanderjeurissen/ranger_devicons \
  ${HOME}/.config/ranger/plugins/ranger_devicons

cd ${HOME}/.config/ranger/plugins/ranger_devicons/
python -m devicons
cd ${HOME}

echo -ne "
------------------------------------------------------------------------------------------
                              Changing Default Console Font
------------------------------------------------------------------------------------------
"
# echo -ne 'KEYMAP="us"
# FONT="ter-v32b"
# ' > /etc/vconsole.conf

echo -ne "
------------------------------------------------------------------------------------------
                                   Disabling Screen Tear
------------------------------------------------------------------------------------------
"
sudo echo -ne 'Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
  Option "TearFree" "true"
EndSection
' > /etc/X11/xorg.conf.d/20-intel.conf

echo -ne "
------------------------------------------------------------------------------------------
                               Updating Touchpad Configuration
------------------------------------------------------------------------------------------
"
sudo echo -ne 'Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Option "Tapping" "True"
    Option "TappingDrag" "True"
    Option "ScrollMethod" "Twofinger"
    Option "NaturalScrolling" "False"
    Option "DisableWhileTyping" "False"
    Driver "libinput"
EndSection
' > /etc/X11/xorg.conf.d/40-libinput.conf

sudo echo -ne "
------------------------------------------------------------------------------------------
                                    Slock Configuration
------------------------------------------------------------------------------------------
"
# sudo echo -ne '[Unit]
# Description=Lock X session using slock for user %i
# Before=sleep.target
#
# [Service]
# User=%i
# Environment=DISPLAY=:0
# ExecStartPre=/usr/bin/xset dpms force suspend
# ExecStart=/usr/local/bin/slock
#
# [Install]
# WantedBy=sleep.target
# ' > /etc/systemd/system/slock@.service
